import esbuild from "esbuild";
import process from "process";
import path from "path";
import { builtinModules } from "node:module";
import compress from "esbuild-compress";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const wsNodeEntry = path.resolve('node_modules/ws/wrapper.mjs');
const wsNodeEntryPlugin = {
	name: 'ws-node-entry',
	setup(build) {
		build.onResolve({ filter: /^ws$/ }, () => ({
			path: wsNodeEntry,
		}));
	},
};

const prod = (process.argv[2] === 'production');
const nodeBuiltins = [
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
];

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	loader: {
		'.md': 'text',
		'.svg': 'text',
		'.png': 'dataurl',
	},
	external: [
		'obsidian',
		'electron',
		'@codemirror/*',
		'@lezer/*',
		...nodeBuiltins
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: "warning",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
	outfile: 'main.js',
	plugins: [
		wsNodeEntryPlugin,
		...(prod ? [
			compress({
				outputDir: '.',
			})
		] : []),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
